### PR TITLE
Fix load OMOP CDM

### LINKED ISSUE #124: OMOP fails to load to DB
There're various errors in loading the omop dataset to the database. Some examples:
1. Tables that are missing from the schema
2. Duplicate keys

### PR DESCRIPTION
**Pull request by guybartal**
## Fixes #124 

This PR fixes load of OMOP CDM to PostgreSQL.

- Remove duplicate table which causes PK constrains
- Remove vocabulary schema as it's not needed, vocabulary tables are in cdm schema in this OMOP version
- Remove commented tests
- Align resource names
- Disable automatic OMOP CDM source creation in Atlas DB, currently admin will need to add source manually via Atlas UI as there's WIP (creation of `user source` role, source permissions and assignments to the created role + refresh source cache - #130 )

### CODE REVIEW

File: infra/sql/add_omop_source.sql [hunk 1]
```diff
@@ -20,4 +20,82 @@ WHERE source_key = '${OMOP_CDM_DATABASE_NAME}';
 INSERT INTO ${WEBAPI_SCHEMA_NAME}.source_daimon (source_daimon_id, source_id, daimon_type, table_qualifier, priority) 
 SELECT nextval('${WEBAPI_SCHEMA_NAME}.source_daimon_sequence'), source_id, 5, '${POSTGRES_OMOP_TEMP_SCHEMA_NAME}', 0
 FROM ${WEBAPI_SCHEMA_NAME}.source
-WHERE source_key = '${OMOP_CDM_DATABASE_NAME}';
\ No newline at end of file
+WHERE source_key = '${OMOP_CDM_DATABASE_NAME}';
+
+-- todo: add source user role
+
+-- Add permissions for the OMOP CDM source
```
Comment (tamirkamara) [inline infra/sql/add_omop_source.sql:27]: Isn't this something ATLAS database seed/migration will do?

I think you have convert all this block to something like this and save half the rows:
```sql
INSERT INTO table_name (column_list)
VALUES
    (value_list_1),
    (value_list_2),
    ...
    (value_list_n);
```

**Review by tamirkamara — APPROVED** [review]

File: infra/sql/add_omop_source.sql (hunk 1 above)
Comment (guybartal) [reply infra/sql/add_omop_source.sql:27]: It's something that WebAPI does when you post new source (can also be done via Atlas UI), 
that's why I've marked out running this sql file in the bash script,
I can remove this file and sort this out later on in #130 preferably via REST call to WebAPI.

Comment (tamirkamara) [reply infra/sql/add_omop_source.sql:27]: Ok
